//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingProduct
    {
        public System.Guid ProductId { get; set; }
        public string ProductName { get; set; }
        public System.Guid ListId { get; set; }
        public Nullable<bool> IsBought { get; set; }
    
        public virtual ShopppingList ShopppingList { get; set; }
    }
}
