//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserList
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ListId { get; set; }
    
        public virtual ShopppingList ShopppingList { get; set; }
        public virtual User User { get; set; }
    }
}
